services:
  - type: web
    name: BOT_1000BONK_L-SUB1
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: BASE_URL
        sync: false